#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VorratsUebersicht.Resource", IsApplication=true)]

namespace VorratsUebersicht
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::VorratsUebersicht.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::VorratsUebersicht.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::VorratsUebersicht.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int ArticleCatagories = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int Application_Background = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Text_Error = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Text_Warning = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Barcode = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_add_a_photo_white_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_add_circle_outline_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_add_shopping_cart_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_add_shopping_cart_white_48dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_assignment_white_48dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_broken_image_white_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_cancel_white_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_check_white_24dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_close_white_24dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_create_white_24dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_delete_white_24dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_insert_photo_white_24dp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_launcher = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_local_offer_white_48dp = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_mode_edit_white_24dp = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_photo_black_24dp = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_photo_camera_black_24dp = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_photo_camera_white_24dp = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_photo_white_24dp = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_remove_circle_outline_white_24dp = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_save_white_24dp = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_search_white_24dp = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_shopping_cart_white_48dp = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_storage_white_48dp = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int splash = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090030
			public const int ArticleDetailHeader = 2131296304;
			
			// aapt resource value: 0x7f090032
			public const int ArticleDetailList = 2131296306;
			
			// aapt resource value: 0x7f090010
			public const int ArticleDetails_ArticleId = 2131296272;
			
			// aapt resource value: 0x7f09000d
			public const int ArticleDetails_Calorie = 2131296269;
			
			// aapt resource value: 0x7f090039
			public const int ArticleDetails_Cancel = 2131296313;
			
			// aapt resource value: 0x7f090006
			public const int ArticleDetails_Category = 2131296262;
			
			// aapt resource value: 0x7f09003b
			public const int ArticleDetails_Delete = 2131296315;
			
			// aapt resource value: 0x7f090008
			public const int ArticleDetails_DurableInfinity = 2131296264;
			
			// aapt resource value: 0x7f09000e
			public const int ArticleDetails_EANCode = 2131296270;
			
			// aapt resource value: 0x7f090001
			public const int ArticleDetails_Image = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int ArticleDetails_Image2 = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int ArticleDetails_ImageText = 2131296259;
			
			// aapt resource value: 0x7f09003c
			public const int ArticleDetails_MakeAPhoto = 2131296316;
			
			// aapt resource value: 0x7f090005
			public const int ArticleDetails_Manufacturer = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int ArticleDetails_Name = 2131296260;
			
			// aapt resource value: 0x7f09000f
			public const int ArticleDetails_Notes = 2131296271;
			
			// aapt resource value: 0x7f09003a
			public const int ArticleDetails_Save = 2131296314;
			
			// aapt resource value: 0x7f09003e
			public const int ArticleDetails_ScanEAN = 2131296318;
			
			// aapt resource value: 0x7f09003d
			public const int ArticleDetails_SelectAPicture = 2131296317;
			
			// aapt resource value: 0x7f09000b
			public const int ArticleDetails_Size = 2131296267;
			
			// aapt resource value: 0x7f090007
			public const int ArticleDetails_SubCategory = 2131296263;
			
			// aapt resource value: 0x7f09000c
			public const int ArticleDetails_Unit = 2131296268;
			
			// aapt resource value: 0x7f09000a
			public const int ArticleDetails_WarnInDays = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int ArticleDetails_WarnInDaysLabel = 2131296265;
			
			// aapt resource value: 0x7f090012
			public const int ArticleImage_Image = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int ArticleImage_Info = 2131296273;
			
			// aapt resource value: 0x7f090013
			public const int ArticleList = 2131296275;
			
			// aapt resource value: 0x7f09003f
			public const int ArticleList_Add = 2131296319;
			
			// aapt resource value: 0x7f090014
			public const int Image = 2131296276;
			
			// aapt resource value: 0x7f090018
			public const int Licenses_Text = 2131296280;
			
			// aapt resource value: 0x7f09001e
			public const int MainButton_Artikeldaten = 2131296286;
			
			// aapt resource value: 0x7f090026
			public const int MainButton_Backup = 2131296294;
			
			// aapt resource value: 0x7f09001f
			public const int MainButton_Barcode = 2131296287;
			
			// aapt resource value: 0x7f090025
			public const int MainButton_Compress = 2131296293;
			
			// aapt resource value: 0x7f090022
			public const int MainButton_DatabasePath = 2131296290;
			
			// aapt resource value: 0x7f09001c
			public const int MainButton_Kategorie = 2131296284;
			
			// aapt resource value: 0x7f09001d
			public const int MainButton_Lagerbestand = 2131296285;
			
			// aapt resource value: 0x7f090028
			public const int MainButton_Licenses = 2131296296;
			
			// aapt resource value: 0x7f090027
			public const int MainButton_Restore = 2131296295;
			
			// aapt resource value: 0x7f090024
			public const int MainButton_RestoreDb0 = 2131296292;
			
			// aapt resource value: 0x7f090023
			public const int MainButton_RestoreSampleDb = 2131296291;
			
			// aapt resource value: 0x7f090020
			public const int MainButton_ShoppingList = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int MainButton_SwitchToTestDB = 2131296289;
			
			// aapt resource value: 0x7f090029
			public const int MainButton_Version = 2131296297;
			
			// aapt resource value: 0x7f090019
			public const int Main_Text = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int Main_Text1 = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int Main_Text2 = 2131296283;
			
			// aapt resource value: 0x7f09002a
			public const int MyListView = 2131296298;
			
			// aapt resource value: 0x7f09002b
			public const int SimpleImageViewText = 2131296299;
			
			// aapt resource value: 0x7f09002d
			public const int StorageItemListView_TextDetails = 2131296301;
			
			// aapt resource value: 0x7f09002c
			public const int StorageItemListView_TextHeader = 2131296300;
			
			// aapt resource value: 0x7f09002e
			public const int StorageItemListView_TextInfo = 2131296302;
			
			// aapt resource value: 0x7f09002f
			public const int StorageItemListView_TextWarning = 2131296303;
			
			// aapt resource value: 0x7f090040
			public const int StorageItemList_Add = 2131296320;
			
			// aapt resource value: 0x7f090036
			public const int StorageItemQuantityList_Add = 2131296310;
			
			// aapt resource value: 0x7f090035
			public const int StorageItemQuantityList_Details = 2131296309;
			
			// aapt resource value: 0x7f090037
			public const int StorageItemQuantityList_Remove = 2131296311;
			
			// aapt resource value: 0x7f090034
			public const int StorageItemQuantityList_Text = 2131296308;
			
			// aapt resource value: 0x7f090033
			public const int StorageItemQuantity_AddArticle = 2131296307;
			
			// aapt resource value: 0x7f090043
			public const int StorageItemQuantity_Cancel = 2131296323;
			
			// aapt resource value: 0x7f090041
			public const int StorageItemQuantity_Edit = 2131296321;
			
			// aapt resource value: 0x7f090042
			public const int StorageItemQuantity_EditPicture = 2131296322;
			
			// aapt resource value: 0x7f090031
			public const int StorageItemQuantity_Image = 2131296305;
			
			// aapt resource value: 0x7f090044
			public const int StorageItemQuantity_Save = 2131296324;
			
			// aapt resource value: 0x7f090015
			public const int Text = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int Text1 = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int Text2 = 2131296279;
			
			// aapt resource value: 0x7f090038
			public const int contentFrame = 2131296312;
			
			// aapt resource value: 0x7f090000
			public const int scroll = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ArticleDetails = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ArticleImage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ArticleList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ArticleListView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Licenses = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int StorageItemList = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int StorageItemListView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int StorageItemQuantity = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int StorageItemQuantityListView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int zxingscanneractivitylayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int zxingscannerfragmentlayout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int ArticleDetails_menu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int ArticleList_menu = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int StorageItemList_menu = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int StorageItemQuantity_menu = 2131230723;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05001f
			public const int ArticleCatagoriesSelect = 2131034143;
			
			// aapt resource value: 0x7f050011
			public const int ArticleDetails_ArticleName = 2131034129;
			
			// aapt resource value: 0x7f05001c
			public const int ArticleDetails_Calories = 2131034140;
			
			// aapt resource value: 0x7f050013
			public const int ArticleDetails_Category = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int ArticleDetails_Category_Hint = 2131034132;
			
			// aapt resource value: 0x7f05001d
			public const int ArticleDetails_EANCode = 2131034141;
			
			// aapt resource value: 0x7f050017
			public const int ArticleDetails_EnduringlyDurable = 2131034135;
			
			// aapt resource value: 0x7f050012
			public const int ArticleDetails_Manufacturer = 2131034130;
			
			// aapt resource value: 0x7f05001e
			public const int ArticleDetails_Notes = 2131034142;
			
			// aapt resource value: 0x7f050019
			public const int ArticleDetails_Size = 2131034137;
			
			// aapt resource value: 0x7f050015
			public const int ArticleDetails_SubCategory = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int ArticleDetails_SubCategory_Hint = 2131034134;
			
			// aapt resource value: 0x7f05001a
			public const int ArticleDetails_Unit = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int ArticleDetails_Unit_Hint = 2131034139;
			
			// aapt resource value: 0x7f050018
			public const int ArticleDetails_WarningInDays = 2131034136;
			
			// aapt resource value: 0x7f050002
			public const int Main_ArticlesNearExpiryDate = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Main_ArticlesWithExpiryDate = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int Main_BackupErstellen = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int Main_BackupZurueckspielen = 2131034127;
			
			// aapt resource value: 0x7f050006
			public const int Main_Button_ArtikelScannen = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int Main_Button_Artikelangaben = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int Main_Button_BestandNachKategorie = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int Main_Button_Lagerbestand = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int Main_Datenbank = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int Main_DatenbankKomprimieren = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int Main_DemnaechstZuVerbrauchen = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int Main_Einkaufsliste = 2131034119;
			
			// aapt resource value: 0x7f050010
			public const int Main_OpenSourceLizenzen = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int Main_Optionen = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int Main_TestDatenbank = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int Main_TestDatenbankLeeren = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int Main_TestDatenbankZuruecksetzen = 2131034123;
			
			// aapt resource value: 0x7f050020
			public const int NoArticleCatagories = 2131034144;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
