#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VorratsUebersicht.Resource", IsApplication=true)]

namespace VorratsUebersicht
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::VorratsUebersicht.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::VorratsUebersicht.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::VorratsUebersicht.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int ArticleCatagories = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050006
			public const int Application_ActionBar_Background = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int Application_ActionBar_TextColor = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int Application_Background = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Application_Background2 = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int Text_Color = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int Text_Color2 = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int Text_Error = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Text_Warning = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Barcode = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int baseline_assignment_late_white_24 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int baseline_error_outline_black_24 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int baseline_error_outline_white_24 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int baseline_folder_white_24 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int baseline_settings_white_24 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int baseline_share_white_24 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_add_a_photo_white_24dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_add_circle_outline_white_24dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_add_shopping_cart_white_24dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_add_shopping_cart_white_48dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_assignment_white_48dp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_broken_image_white_24dp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_cancel_white_24dp = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_check_white_24dp = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_close_white_24dp = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_create_white_24dp = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_delete_white_24dp = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_insert_photo_white_24dp = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_launcher = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_local_offer_white_48dp = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_mode_edit_white_24dp = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_photo_black_24dp = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_photo_camera_black_24dp = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_photo_camera_white_24dp = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_photo_white_24dp = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_remove_circle_outline_white_24dp = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_save_white_24dp = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_search_white_24dp = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_shopping_cart_white_48dp = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_storage_white_48dp = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int outline_assignment_late_white_24 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int outline_rotate_right_white_24 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int splash = 2130837538;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0053
			public const int ArticleDetailHeader = 2131361875;
			
			// aapt resource value: 0x7f0a0055
			public const int ArticleDetailList = 2131361877;
			
			// aapt resource value: 0x7f0a005f
			public const int ArticleDetailsMenu_Cancel = 2131361887;
			
			// aapt resource value: 0x7f0a0061
			public const int ArticleDetailsMenu_Delete = 2131361889;
			
			// aapt resource value: 0x7f0a0062
			public const int ArticleDetailsMenu_MakeAPhoto = 2131361890;
			
			// aapt resource value: 0x7f0a0060
			public const int ArticleDetailsMenu_Save = 2131361888;
			
			// aapt resource value: 0x7f0a0065
			public const int ArticleDetailsMenu_ScanEAN = 2131361893;
			
			// aapt resource value: 0x7f0a0063
			public const int ArticleDetailsMenu_SelectAPicture = 2131361891;
			
			// aapt resource value: 0x7f0a0064
			public const int ArticleDetailsMenu_ShowPicture = 2131361892;
			
			// aapt resource value: 0x7f0a0067
			public const int ArticleDetailsMenu_Speech = 2131361895;
			
			// aapt resource value: 0x7f0a0066
			public const int ArticleDetailsMenu_ToShoppingList = 2131361894;
			
			// aapt resource value: 0x7f0a001a
			public const int ArticleDetails_ArticleId = 2131361818;
			
			// aapt resource value: 0x7f0a0015
			public const int ArticleDetails_Calorie = 2131361813;
			
			// aapt resource value: 0x7f0a0013
			public const int ArticleDetails_CaloriePerUnit = 2131361811;
			
			// aapt resource value: 0x7f0a0012
			public const int ArticleDetails_CaloriePerUnitLabel = 2131361810;
			
			// aapt resource value: 0x7f0a0011
			public const int ArticleDetails_CaloriesPerUnitSection = 2131361809;
			
			// aapt resource value: 0x7f0a0014
			public const int ArticleDetails_CaloriesSection = 2131361812;
			
			// aapt resource value: 0x7f0a0007
			public const int ArticleDetails_Category = 2131361799;
			
			// aapt resource value: 0x7f0a000b
			public const int ArticleDetails_DurableInfinity = 2131361803;
			
			// aapt resource value: 0x7f0a0018
			public const int ArticleDetails_EANCode = 2131361816;
			
			// aapt resource value: 0x7f0a0001
			public const int ArticleDetails_Image = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int ArticleDetails_Image2 = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int ArticleDetails_ImageText = 2131361795;
			
			// aapt resource value: 0x7f0a0006
			public const int ArticleDetails_Manufacturer = 2131361798;
			
			// aapt resource value: 0x7f0a0016
			public const int ArticleDetails_MinQuantity = 2131361814;
			
			// aapt resource value: 0x7f0a0005
			public const int ArticleDetails_Name = 2131361797;
			
			// aapt resource value: 0x7f0a0019
			public const int ArticleDetails_Notes = 2131361817;
			
			// aapt resource value: 0x7f0a0017
			public const int ArticleDetails_PrefQuantity = 2131361815;
			
			// aapt resource value: 0x7f0a000e
			public const int ArticleDetails_Price = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int ArticleDetails_Size = 2131361807;
			
			// aapt resource value: 0x7f0a000a
			public const int ArticleDetails_Storage = 2131361802;
			
			// aapt resource value: 0x7f0a0008
			public const int ArticleDetails_SubCategory = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int ArticleDetails_Supermarket = 2131361801;
			
			// aapt resource value: 0x7f0a0010
			public const int ArticleDetails_Unit = 2131361808;
			
			// aapt resource value: 0x7f0a000d
			public const int ArticleDetails_WarnInDays = 2131361805;
			
			// aapt resource value: 0x7f0a000c
			public const int ArticleDetails_WarnInDaysLabel = 2131361804;
			
			// aapt resource value: 0x7f0a0068
			public const int ArticleImageMenu_RotateRight = 2131361896;
			
			// aapt resource value: 0x7f0a001c
			public const int ArticleImage_Image = 2131361820;
			
			// aapt resource value: 0x7f0a001b
			public const int ArticleImage_Info = 2131361819;
			
			// aapt resource value: 0x7f0a0021
			public const int ArticleList = 2131361825;
			
			// aapt resource value: 0x7f0a006a
			public const int ArticleList_Add = 2131361898;
			
			// aapt resource value: 0x7f0a001f
			public const int ArticleList_Categories = 2131361823;
			
			// aapt resource value: 0x7f0a001e
			public const int ArticleList_Category = 2131361822;
			
			// aapt resource value: 0x7f0a0020
			public const int ArticleList_Footer = 2131361824;
			
			// aapt resource value: 0x7f0a0069
			public const int ArticleList_Search = 2131361897;
			
			// aapt resource value: 0x7f0a001d
			public const int ArticleList_SelectCategory = 2131361821;
			
			// aapt resource value: 0x7f0a0022
			public const int Image = 2131361826;
			
			// aapt resource value: 0x7f0a0027
			public const int Licenses_Text = 2131361831;
			
			// aapt resource value: 0x7f0a002e
			public const int MainButton_Artikeldaten = 2131361838;
			
			// aapt resource value: 0x7f0a002f
			public const int MainButton_Barcode = 2131361839;
			
			// aapt resource value: 0x7f0a002c
			public const int MainButton_Kategorie = 2131361836;
			
			// aapt resource value: 0x7f0a002d
			public const int MainButton_Lagerbestand = 2131361837;
			
			// aapt resource value: 0x7f0a0030
			public const int MainButton_ShoppingList = 2131361840;
			
			// aapt resource value: 0x7f0a006b
			public const int Main_Menu_Options = 2131361899;
			
			// aapt resource value: 0x7f0a0028
			public const int Main_Text = 2131361832;
			
			// aapt resource value: 0x7f0a0029
			public const int Main_Text1 = 2131361833;
			
			// aapt resource value: 0x7f0a002a
			public const int Main_Text2 = 2131361834;
			
			// aapt resource value: 0x7f0a002b
			public const int Main_TextInfo = 2131361835;
			
			// aapt resource value: 0x7f0a004d
			public const int MyListView = 2131361869;
			
			// aapt resource value: 0x7f0a0004
			public const int ProgressBar = 2131361796;
			
			// aapt resource value: 0x7f0a0039
			public const int ProgressBar_BackupAndRestore = 2131361849;
			
			// aapt resource value: 0x7f0a0036
			public const int ProgressBar_Compress = 2131361846;
			
			// aapt resource value: 0x7f0a003d
			public const int ProgressBar_RestoreSampleDb = 2131361853;
			
			// aapt resource value: 0x7f0a0034
			public const int SelectFile = 2131361844;
			
			// aapt resource value: 0x7f0a0032
			public const int SelectFile_Button = 2131361842;
			
			// aapt resource value: 0x7f0a0033
			public const int SelectFile_Message = 2131361843;
			
			// aapt resource value: 0x7f0a0031
			public const int SelectFile_Path = 2131361841;
			
			// aapt resource value: 0x7f0a003a
			public const int SettingsButton_Backup = 2131361850;
			
			// aapt resource value: 0x7f0a0037
			public const int SettingsButton_Compress = 2131361847;
			
			// aapt resource value: 0x7f0a0035
			public const int SettingsButton_DatabasePath = 2131361845;
			
			// aapt resource value: 0x7f0a0041
			public const int SettingsButton_Licenses = 2131361857;
			
			// aapt resource value: 0x7f0a003b
			public const int SettingsButton_Restore = 2131361851;
			
			// aapt resource value: 0x7f0a003f
			public const int SettingsButton_RestoreDb0 = 2131361855;
			
			// aapt resource value: 0x7f0a003e
			public const int SettingsButton_RestoreSampleDb = 2131361854;
			
			// aapt resource value: 0x7f0a0040
			public const int SettingsButton_SwitchToAppDb = 2131361856;
			
			// aapt resource value: 0x7f0a003c
			public const int SettingsButton_SwitchToTestDB = 2131361852;
			
			// aapt resource value: 0x7f0a0042
			public const int SettingsButton_Version = 2131361858;
			
			// aapt resource value: 0x7f0a0038
			public const int Settings_Categories = 2131361848;
			
			// aapt resource value: 0x7f0a0046
			public const int ShoppingItemList = 2131361862;
			
			// aapt resource value: 0x7f0a0045
			public const int ShoppingItemList_Footer = 2131361861;
			
			// aapt resource value: 0x7f0a0043
			public const int ShoppingItemList_SelectSupermarket = 2131361859;
			
			// aapt resource value: 0x7f0a0044
			public const int ShoppingItemList_Spinner = 2131361860;
			
			// aapt resource value: 0x7f0a006d
			public const int ShoppingList_Add = 2131361901;
			
			// aapt resource value: 0x7f0a006c
			public const int ShoppingList_Search = 2131361900;
			
			// aapt resource value: 0x7f0a006e
			public const int ShoppingList_Share = 2131361902;
			
			// aapt resource value: 0x7f0a006f
			public const int ShoppingList_popup_Add1 = 2131361903;
			
			// aapt resource value: 0x7f0a0070
			public const int ShoppingList_popup_Less1 = 2131361904;
			
			// aapt resource value: 0x7f0a004e
			public const int SimpleImageViewText = 2131361870;
			
			// aapt resource value: 0x7f0a0048
			public const int SplashScreen_ProgressBar = 2131361864;
			
			// aapt resource value: 0x7f0a0047
			public const int SplashScreen_ProgressText = 2131361863;
			
			// aapt resource value: 0x7f0a0050
			public const int StorageItemListView_TextDetails = 2131361872;
			
			// aapt resource value: 0x7f0a004f
			public const int StorageItemListView_TextHeader = 2131361871;
			
			// aapt resource value: 0x7f0a0051
			public const int StorageItemListView_TextInfo = 2131361873;
			
			// aapt resource value: 0x7f0a0052
			public const int StorageItemListView_TextWarning = 2131361874;
			
			// aapt resource value: 0x7f0a0073
			public const int StorageItemList_Add = 2131361907;
			
			// aapt resource value: 0x7f0a0072
			public const int StorageItemList_Filter = 2131361906;
			
			// aapt resource value: 0x7f0a004c
			public const int StorageItemList_Footer = 2131361868;
			
			// aapt resource value: 0x7f0a0071
			public const int StorageItemList_Search = 2131361905;
			
			// aapt resource value: 0x7f0a0049
			public const int StorageItemList_SelectStorageSection = 2131361865;
			
			// aapt resource value: 0x7f0a004b
			public const int StorageItemList_Storages = 2131361867;
			
			// aapt resource value: 0x7f0a004a
			public const int StorageItemList_TextStorage = 2131361866;
			
			// aapt resource value: 0x7f0a0056
			public const int StorageItemQuantity = 2131361878;
			
			// aapt resource value: 0x7f0a005c
			public const int StorageItemQuantityList_Add = 2131361884;
			
			// aapt resource value: 0x7f0a005b
			public const int StorageItemQuantityList_Details = 2131361883;
			
			// aapt resource value: 0x7f0a005d
			public const int StorageItemQuantityList_Remove = 2131361885;
			
			// aapt resource value: 0x7f0a005a
			public const int StorageItemQuantityList_Text = 2131361882;
			
			// aapt resource value: 0x7f0a0059
			public const int StorageItemQuantity_AddArticle = 2131361881;
			
			// aapt resource value: 0x7f0a0076
			public const int StorageItemQuantity_Cancel = 2131361910;
			
			// aapt resource value: 0x7f0a0074
			public const int StorageItemQuantity_Edit = 2131361908;
			
			// aapt resource value: 0x7f0a0075
			public const int StorageItemQuantity_EditPicture = 2131361909;
			
			// aapt resource value: 0x7f0a0054
			public const int StorageItemQuantity_Image = 2131361876;
			
			// aapt resource value: 0x7f0a0077
			public const int StorageItemQuantity_Save = 2131361911;
			
			// aapt resource value: 0x7f0a0057
			public const int StorageItemQuantity_StepButton = 2131361879;
			
			// aapt resource value: 0x7f0a0058
			public const int StorageItemQuantity_StepText = 2131361880;
			
			// aapt resource value: 0x7f0a0078
			public const int StorageItemQuantity_ToShoppingList = 2131361912;
			
			// aapt resource value: 0x7f0a0023
			public const int Text = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public const int Text1 = 2131361828;
			
			// aapt resource value: 0x7f0a0025
			public const int Text2 = 2131361829;
			
			// aapt resource value: 0x7f0a0026
			public const int Text3 = 2131361830;
			
			// aapt resource value: 0x7f0a005e
			public const int contentFrame = 2131361886;
			
			// aapt resource value: 0x7f0a0000
			public const int scroll = 2131361792;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ArticleDetails = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ArticleImage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ArticleList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ArticleListView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Licenses = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SelectFile = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Settings = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ShoppingItemList = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SplashScreen = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int StorageItemList = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int StorageItemListView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int StorageItemQuantity = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int StorageItemQuantityListView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int zxingscanneractivitylayout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int zxingscannerfragmentlayout = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int ArticleDetails_menu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int ArticleImage_menu = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int ArticleList_menu = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int Main_menu = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int ShoppingList_menu = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int ShoppingList_popup = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int StorageItemList_menu = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int StorageItemQuantity_menu = 2131296263;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int DelFromEmulator = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int DelFromEmulator2 = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06003c
			public const int AnySubCategory_ItemEntry = 2131099708;
			
			// aapt resource value: 0x7f060004
			public const int App_Cancel = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int App_Name = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int App_No = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int App_Ok = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int App_Save = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int App_Yes = 2131099649;
			
			// aapt resource value: 0x7f060039
			public const int ArticleCatagoriesSelect = 2131099705;
			
			// aapt resource value: 0x7f060036
			public const int ArticleDetails_Amount = 2131099702;
			
			// aapt resource value: 0x7f060022
			public const int ArticleDetails_ArticleName = 2131099682;
			
			// aapt resource value: 0x7f06002d
			public const int ArticleDetails_Calories = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int ArticleDetails_CaloriesPerUnit = 2131099694;
			
			// aapt resource value: 0x7f060024
			public const int ArticleDetails_Category = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int ArticleDetails_Category_Hint = 2131099685;
			
			// aapt resource value: 0x7f060034
			public const int ArticleDetails_EANCode = 2131099700;
			
			// aapt resource value: 0x7f060028
			public const int ArticleDetails_EnduringlyDurable = 2131099688;
			
			// aapt resource value: 0x7f060023
			public const int ArticleDetails_Manufacturer = 2131099683;
			
			// aapt resource value: 0x7f06001e
			public const int ArticleDetails_Menu_CreatePicture = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int ArticleDetails_Menu_DeleteArticle = 2131099677;
			
			// aapt resource value: 0x7f060021
			public const int ArticleDetails_Menu_EAN_Scannen = 2131099681;
			
			// aapt resource value: 0x7f06001f
			public const int ArticleDetails_Menu_SelectPicture = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int ArticleDetails_Menu_ShowPicture = 2131099680;
			
			// aapt resource value: 0x7f060030
			public const int ArticleDetails_MinQuantityLabel = 2131099696;
			
			// aapt resource value: 0x7f060035
			public const int ArticleDetails_Notes = 2131099701;
			
			// aapt resource value: 0x7f060031
			public const int ArticleDetails_PrefQuantityLabel = 2131099697;
			
			// aapt resource value: 0x7f060033
			public const int ArticleDetails_Price = 2131099699;
			
			// aapt resource value: 0x7f06002a
			public const int ArticleDetails_Size = 2131099690;
			
			// aapt resource value: 0x7f06002f
			public const int ArticleDetails_StorageLabel = 2131099695;
			
			// aapt resource value: 0x7f060026
			public const int ArticleDetails_SubCategory = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int ArticleDetails_SubCategory_Hint = 2131099687;
			
			// aapt resource value: 0x7f060032
			public const int ArticleDetails_SupermarketLabel = 2131099698;
			
			// aapt resource value: 0x7f06002b
			public const int ArticleDetails_Unit = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int ArticleDetails_Unit_Hint = 2131099692;
			
			// aapt resource value: 0x7f060029
			public const int ArticleDetails_WarningInDays = 2131099689;
			
			// aapt resource value: 0x7f06001c
			public const int ArticleList_AllCategories = 2131099676;
			
			// aapt resource value: 0x7f06000c
			public const int Main_ArticlesNearExpiryDate = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int Main_ArticlesWithExpiryDate = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int Main_Button_ArtikelListe = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int Main_Button_ArtikelScannen = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int Main_Button_Artikelangaben = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int Main_Button_BestandNachKategorie = 2131099661;
			
			// aapt resource value: 0x7f060012
			public const int Main_Button_Einkaufsliste = 2131099666;
			
			// aapt resource value: 0x7f06000e
			public const int Main_Button_Lagerbestand = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int Main_DemnaechstZuVerbrauchen = 2131099658;
			
			// aapt resource value: 0x7f06003a
			public const int NoArticleCatagories = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int NoSubCategory_ItemEntry = 2131099707;
			
			// aapt resource value: 0x7f060019
			public const int Settings_CreateBackup = 2131099673;
			
			// aapt resource value: 0x7f060015
			public const int Settings_Datenbank = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int Settings_DatenbankKomprimieren = 2131099672;
			
			// aapt resource value: 0x7f06001b
			public const int Settings_OpenSourceLizenzen = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int Settings_RestoreBackup = 2131099674;
			
			// aapt resource value: 0x7f060014
			public const int Settings_TestDatenbank = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int Settings_TestDatenbankLeeren = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int Settings_TestDatenbankZuruecksetzen = 2131099670;
			
			// aapt resource value: 0x7f060013
			public const int Settings_Title = 2131099667;
			
			// aapt resource value: 0x7f06003f
			public const int ShoppingList_AllSupermarkets = 2131099711;
			
			// aapt resource value: 0x7f06003d
			public const int ShoppingList_Remove = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int ShoppingList_ToStorage = 2131099710;
			
			// aapt resource value: 0x7f060006
			public const int Start_TestDbQuestion = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int Start_TestVersionInfo1 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int Start_TestVersionInfo2 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int Start_TestVersionInfo3 = 2131099657;
			
			// aapt resource value: 0x7f060038
			public const int StorageItemQuantity_Menu_ToShoppingList = 2131099704;
			
			// aapt resource value: 0x7f060037
			public const int StorageItem_AllStoragesStorage = 2131099703;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Theme_Splash = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
